name: Update helloword

on:
  repository_dispatch:
  release:
    types: published
#  push:
#    branches:
#      - main
  schedule:
    - cron: 1 0 */3 * *
  watch:
    types: started
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  merge:
    runs-on: Ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install git subversion git-core wget
        sudo timedatectl set-timezone "$TZ"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
    - name: Clone packages
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x helloword.sh
        git clone https://github.com/firkerword/openwrt_helloworld.git openwrt_helloworld
        cd openwrt_helloworld
        $GITHUB_WORKSPACE/helloword.sh
    - name: Upload
      run: |
        [ -e $GITHUB_WORKSPACE/README.md ] && cp $GITHUB_WORKSPACE/README.md $GITHUB_WORKSPACE/openwrt_helloworld
        cd $GITHUB_WORKSPACE/openwrt_helloworld
        git add .
        git commit -m "update$(TZ='Asia/Shanghai' date +@%Y%m%d)"
        git push --quiet "https://${{ secrets.TOKEN }}@github.com/firkerword/openwrt_helloworld.git"
 
